import React, { useState } from 'react';
import { Row, Col, Card, Badge, Button, OverlayTrigger, Tooltip as BootstrapTooltip } from 'react-bootstrap';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Legend, ResponsiveContainer } from 'recharts';
import { FiTruck, FiHeart, FiVideo, FiTrendingDown, FiTrendingUp, FiUsers, FiAward, FiDownload, FiShield, FiActivity, FiInfo } from 'react-icons/fi';

const handleExportBRSR = (companyName, stats) => {
  if (!stats) return;
  const g = stats.greenTrail || {};
  const exportContent = `
BRSR CORE COMPLIANCE REPORT
============================
Company: ${companyName.toUpperCase()}
Report Period: FY 2025-26
Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}
Generated By: GreenVerse ESG Command Center
Standard: SEBI BRSR Core (Reasonable Assurance)

SECTION A — SCOPE 3 EMPLOYEE COMMUTING EMISSIONS
--------------------------------------------------
Total CO₂ Generated by Workforce:    ${g.totalCO2Generated || 0} kg CO₂e
Total CO₂ Offset by Workforce:       ${g.totalCO2Offset || 0} kg CO₂e
  → Tree Planting:                   ${g.treeOffset || 0} kg CO₂e
  → Carpooling:                      ${g.carpoolOffset || 0} kg CO₂e
  → Food Rescue:                     ${g.foodOffset || 0} kg CO₂e
Net CO₂ Emissions (BRSR Reportable): ${g.netCO2 || 0} kg CO₂e
Verification Method:                  Geo-fence + GPS + Platform Activity Logs

SECTION B — WORKFORCE ESG PARTICIPATION
--------------------------------------------------
Active Employees on Platform:         ${stats.activeEmployees || 0}
GreenStream Training Videos Watched:  ${stats.ecoLearn?.totalViews || 0} views
Total Videos Uploaded:                ${stats.ecoLearn?.totalVideos || 0} videos

SECTION C — ENVIRONMENTAL INITIATIVES
--------------------------------------------------
Trees Sponsored by Workforce:         ${g.totalTrees || 0} trees
Total Carpool Rides Verified:         ${stats.carpooling?.totalRides || 0} rides
Food Waste Prevented:                 ${stats.foodWaste?.mealsSaved || 0} meals rescued

SECTION D — INTERNAL CARBON ECONOMY
--------------------------------------------------
Total ICTs Earned by Employees:       ${stats.ictSummary?.totalICT || 0} tokens
Monthly Carbon Budget (All Dept):     ${stats.ictSummary?.budgetICT || 0} kg CO₂e
Estimated HR Perk Value Distributed:  ₹${(stats.ictSummary?.perkValue || 0).toLocaleString('en-IN')}

COMPLIANCE STATUS: ✅ ON TRACK FOR SEBI BRSR CORE FY2026-27
Assurance Level: Reasonable Assurance (as mandated for Top 1000 listed entities)

--------------------------------------------------
This report was auto-generated by GreenVerse Enterprise ESG Platform.
  `;
  const blob = new Blob([exportContent], { type: 'text/plain' });
  const url  = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href  = url;
  link.download = `BRSR_Core_Report_${companyName.toUpperCase()}_FY2025-26.txt`;
  link.click();
  URL.revokeObjectURL(url);
};

const ESGAnalyticsView = ({ stats, companyName }) => {
  const [exportClicked, setExportClicked] = useState(false);

  const handleExportClick = () => {
    setExportClicked(true);
    handleExportBRSR(companyName, stats);
    setTimeout(() => setExportClicked(false), 3000);
  };

  const renderDeptTooltip = (dataKey, title) => (
    <BootstrapTooltip id={`tooltip-${dataKey}`} style={{ textAlign: 'left', fontSize: '0.85rem' }}>
      <div style={{ padding: '6px' }}>
        <strong style={{ display: 'block', borderBottom: '1px solid rgba(255,255,255,0.2)', paddingBottom: '6px', marginBottom: '8px' }}>
          {title} Breakdown
        </strong>
        {(stats?.departmentData || []).filter(d => (dataKey === 'activeUsers' ? (d.budgetKg / 450) : d[dataKey]) > 0).length > 0 ? (
          (stats.departmentData).filter(d => (dataKey === 'activeUsers' ? (d.budgetKg / 450) : d[dataKey]) > 0).map((d, i) => {
            const val = dataKey === 'activeUsers' ? (d.activeUsers || (d.budgetKg / 450)) : d[dataKey];
            return (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', gap: '20px', marginBottom: '6px' }}>
                <span style={{ textTransform: 'capitalize' }}>{d.department}:</span>
                <strong>{Number(val).toLocaleString()} {dataKey !== 'activeUsers' ? 'kg' : 'Users'}</strong>
              </div>
            );
          })
        ) : (
          <div style={{ fontStyle: 'italic', color: 'rgba(255,255,255,0.6)' }}>No data available</div>
        )}
      </div>
    </BootstrapTooltip>
  );

  const g = stats.greenTrail || {};
  const ict = stats.ictSummary || { totalICT: 0, budgetICT: 1, perkValue: 0, totalEmissions: 0, totalOffset: 0, netCO2: 0 };
  const budgetUsedPercent = Math.min(100, Math.round((ict.netCO2 / Math.max(1, ict.budgetICT)) * 100));
  const deptCapTrade = (stats.departmentData || []).map(d => ({ ...d, surplus: (d.budgetKg || 0) - (d.netKg || 0) }));

  return (
    <>
      <div className="text-center mb-5">
        <h2 className="gt-dashboard-title text-white fw-bold mb-2" style={{ fontSize: '3rem' }}>
          🏢 {companyName} ESG Analytics
        </h2>
        <div className="gt-title-underline"></div>
        <Badge bg="success" className="mt-3 p-2 fs-6 shadow me-2">Verified Enterprise Partner</Badge>
        <Badge bg="primary" className="mt-3 p-2 fs-6 shadow">SEBI BRSR Core Compliant</Badge>
        <div className="mt-4">
          <Button onClick={handleExportClick} disabled={exportClicked} className="gt-brsr-export-btn"
            style={{
              background: exportClicked ? 'linear-gradient(135deg,#1b5e20,#2e7d32)' : 'linear-gradient(135deg,#0d47a1,#1565c0)',
              border: 'none', borderRadius: '50px', padding: '14px 36px',
              fontSize: '1rem', fontWeight: '700', color: '#fff',
              boxShadow: exportClicked ? '0 0 30px rgba(46,204,113,0.6)' : '0 0 20px rgba(21,101,192,0.5)',
            }}>
            {exportClicked ? <><FiShield className="me-2" />✅ BRSR Report Generated!</> : <><FiDownload className="me-2" />Export SEBI BRSR Core Report</>}
          </Button>
          <p style={{ color: 'rgba(255,255,255,0.45)', fontSize: '0.75rem', marginTop: '8px' }}>
            One-click export · FY 2025-26 · Reasonable Assurance Standard
          </p>
        </div>
      </div>

      <Row className="g-4 mb-4">
        <Col md={3}>
          <Card className="gt-eco-card h-100 border-start border-danger border-4">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-start mb-2">
                <div className="text-danger"><FiTrendingUp size={30} /></div>
                <Badge bg="danger">YTD Total</Badge>
              </div>
              <div className="d-flex align-items-center gap-2 mb-1">
                <h5 className="card-title text-white text-start mb-0">CO₂ GENERATED</h5>
                <OverlayTrigger placement="top" overlay={renderDeptTooltip('emissionsKg', 'Generated CO₂')}>
                  <span style={{ cursor: "help", color: "rgba(255,255,255,0.5)" }}><FiInfo size={16} /></span>
                </OverlayTrigger>
              </div>
              <p className="card-text fs-2 text-white fw-bold text-start mb-1">
                {g.totalCO2Generated || 0} <span className="fs-6 text-white-50">kg</span>
              </p>
              <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.72rem', margin: 0 }}>Sum of all employee footprints</p>
            </Card.Body>
          </Card>
        </Col>

        <Col md={3}>
          <Card className="gt-eco-card h-100 border-start border-success border-4">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-start mb-2">
                <div className="text-success"><FiTrendingDown size={30} /></div>
                <Badge bg="success">Offset</Badge>
              </div>
              <div className="d-flex align-items-center gap-2 mb-1">
                <h5 className="card-title text-white text-start mb-0">CO₂ OFFSET</h5>
                <OverlayTrigger placement="top" overlay={renderDeptTooltip('offsetKg', 'Offset CO₂')}>
                  <span style={{ cursor: "help", color: "rgba(255,255,255,0.5)" }}><FiInfo size={16} /></span>
                </OverlayTrigger>
              </div>
              <p className="card-text fs-2 text-white fw-bold text-start mb-1">
                {g.totalCO2Offset || 0} <span className="fs-6 text-white-50">kg</span>
              </p>
              <div style={{ fontSize: '0.72rem', color: 'rgba(255,255,255,0.4)', lineHeight: '1.6' }}>
                <div>🌳 Trees: {g.treeOffset || 0} kg</div>
                <div>🚗 Carpool: {g.carpoolOffset || 0} kg</div>
                <div>🍲 Food: {Math.round(g.foodOffset || 0)} kg</div>
              </div>
            </Card.Body>
          </Card>
        </Col>

        <Col md={3}>
          <Card className="gt-eco-card h-100 border-start border-warning border-4">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-start mb-2">
                <div className="text-warning"><FiActivity size={30} /></div>
                <Badge bg="warning" text="dark">BRSR</Badge>
              </div>
              <div className="d-flex align-items-center gap-2 mb-1">
                <h5 className="card-title text-white text-start mb-0">NET CO₂ (REPORTABLE)</h5>
                <OverlayTrigger placement="top" overlay={renderDeptTooltip('netKg', 'Net CO₂')}>
                  <span style={{ cursor: "help", color: "rgba(255,255,255,0.5)" }}><FiInfo size={16} /></span>
                </OverlayTrigger>
              </div>
              <p className="card-text fs-2 fw-bold text-start mb-1" style={{ color: ict.netCO2 > ict.budgetICT ? '#ff5252' : '#69f0ae' }}>
                {g.netCO2 || 0} <span className="fs-6 text-white-50">kg</span>
              </p>
              <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.72rem', margin: 0 }}>Generated − Offset</p>
            </Card.Body>
          </Card>
        </Col>

        <Col md={3}>
          <Card className="gt-eco-card h-100 border-start border-info border-4">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-start mb-2">
                <div className="text-info"><FiUsers size={30} /></div>
                <Badge bg="info">Workforce</Badge>
              </div>
              <div className="d-flex align-items-center gap-2 mb-1">
                <h5 className="card-title text-white text-start mb-0">ACTIVE EMPLOYEES</h5>
                <OverlayTrigger placement="top" overlay={renderDeptTooltip('activeUsers', 'Active Employees')}>
                  <span style={{ cursor: "help", color: "rgba(255,255,255,0.5)" }}><FiInfo size={16} /></span>
                </OverlayTrigger>
              </div>
              <p className="card-text fs-2 text-white fw-bold text-start mb-0">
                {stats.activeEmployees || 0} <span className="fs-6 text-white-50">Users</span>
              </p>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      <Row className="g-4 mb-5">
        <Col md={3}>
          <Card className="gt-eco-card h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-start mb-2">
                <div className="text-warning"><FiAward size={28} /></div>
                <Badge bg="warning" text="dark">Trees</Badge>
              </div>
              <h5 className="card-title text-white text-start">TREES SPONSORED</h5>
              <p className="card-text fs-2 text-white fw-bold text-start mb-0">
                {g.totalTrees || 0} <span className="fs-6 text-white-50">planted</span>
              </p>
            </Card.Body>
          </Card>
        </Col>
        <Col md={3}>
          <Card className="gt-eco-card h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-center mb-3">
                <FiTruck size={28} className="text-primary" />
                <span className="text-white-50 fw-bold" style={{ fontSize: '0.75rem' }}>CARPOOLING</span>
              </div>
              <h2 className="text-white fw-bold mb-0">{stats.carpooling?.totalRides || 0} Rides</h2>
              <p className="text-primary fw-bold mb-0" style={{ fontSize: '0.85rem' }}>
                ≈ {stats.carpooling?.co2Saved || 0} kg CO₂ offset
              </p>
            </Card.Body>
          </Card>
        </Col>
        <Col md={3}>
          <Card className="gt-eco-card h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-center mb-3">
                <FiHeart size={28} className="text-warning" />
                <span className="text-white-50 fw-bold" style={{ fontSize: '0.75rem' }}>FOOD RESCUE</span>
              </div>
              <h2 className="text-white fw-bold mb-0">{stats.foodWaste?.mealsSaved || 0} Meals</h2>
              <p className="text-warning fw-bold mb-0" style={{ fontSize: '0.85rem' }}>
                {stats.foodWaste?.totalDonations || 0} Active Donors
              </p>
            </Card.Body>
          </Card>
        </Col>
        <Col md={3}>
          <Card className="gt-eco-card h-100">
            <Card.Body>
              <div className="d-flex justify-content-between align-items-center mb-3">
                <FiVideo size={28} style={{ color: '#9b59b6' }} />
                <span className="text-white-50 fw-bold" style={{ fontSize: '0.75rem' }}>GREENSTREAM</span>
              </div>
              <h2 className="text-white fw-bold mb-0">{stats.ecoLearn?.totalVideos || 0} Videos</h2>
              <p className="fw-bold mb-0" style={{ color: '#9b59b6', fontSize: '0.85rem' }}>
                {stats.ecoLearn?.totalViews || 0} Total Views
              </p>
            </Card.Body>
          </Card>
        </Col>
      </Row>

      <Row className="g-4 mb-5">
        <Col md={8}>
          <div className="gt-graph-wrapper p-4 rounded-4 shadow-lg h-100" style={{ background: 'rgba(15,30,20,0.7)', backdropFilter: 'blur(15px)', border: '1px solid rgba(255,255,255,0.1)' }}>
            <h4 className="text-white mb-1 fw-bold">Monthly CO₂: Generated vs Offset vs Net (Tons)</h4>
            <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.78rem', marginBottom: '20px' }}>
              Red = emitted by workforce · Green = offset by actions · Yellow = net reportable (BRSR)
            </p>
            <div style={{ height: '300px' }}>
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={stats.emissionTargets || []} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" />
                  <XAxis dataKey="month" stroke="#ffffff" />
                  <YAxis stroke="#ffffff" />
                  <RechartsTooltip contentStyle={{ backgroundColor: 'rgba(15,30,20,0.9)', border: '1px solid #2ecc71', borderRadius: '10px', color: '#fff' }} />
                  <Legend wrapperStyle={{ paddingTop: '10px', color: '#fff' }} />
                  <Line type="monotone" dataKey="target"    stroke="#e74c3c" name="Monthly Budget (Tons)" strokeWidth={2} strokeDasharray="5 5" />
                  <Line type="monotone" dataKey="generated" stroke="#ff7043" name="CO₂ Generated (Tons)" strokeWidth={3} />
                  <Line type="monotone" dataKey="offset"    stroke="#2ecc71" name="CO₂ Offset (Tons)"    strokeWidth={3} />
                  <Line type="monotone" dataKey="net"       stroke="#ffd54f" name="Net CO₂ (Tons)"       strokeWidth={4} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </div>
        </Col>

        <Col md={4}>
          <div className="gt-graph-wrapper p-4 rounded-4 shadow-lg h-100" style={{ background: 'rgba(15,30,20,0.7)', backdropFilter: 'blur(15px)', border: '1px solid rgba(255,255,255,0.1)' }}>
            <h4 className="text-white mb-1 fw-bold">Net Emissions by Dept</h4>
            <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.78rem', marginBottom: '16px' }}>kg CO₂e net per department</p>
            <div style={{ height: '300px' }}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={stats.departmentData || []} layout="vertical" margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" horizontal={true} vertical={false} />
                  <XAxis type="number" stroke="#ffffff" />
                  <YAxis dataKey="department" type="category" width={80} stroke="#ffffff" />
                  <RechartsTooltip contentStyle={{ backgroundColor: 'rgba(15,30,20,0.9)', border: '1px solid #3498db', borderRadius: '10px', color: '#fff' }} />
                  <Bar dataKey="netKg"    fill="#ff7043" name="Net CO₂ (kg)"    radius={[0, 4, 4, 0]} />
                  <Bar dataKey="budgetKg" fill="rgba(46,204,113,0.25)" name="Budget (kg)" radius={[0, 4, 4, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </Col>
      </Row>

      <Row className="g-4 mb-5">
        <Col md={12}>
          <div className="gt-graph-wrapper p-4 rounded-4 shadow-lg" style={{ background: 'rgba(15,30,20,0.7)', backdropFilter: 'blur(15px)', border: '1px solid rgba(46,204,113,0.3)' }}>
            <div className="d-flex justify-content-between align-items-center mb-4 flex-wrap gap-3">
              <div>
                <h4 className="text-white fw-bold mb-1">💹 Departmental Carbon Cap-and-Trade Floor</h4>
                <p style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.78rem', margin: 0 }}>Budget = 450 kg CO₂e per employee per month · Net = Generated − Offset</p>
              </div>
            </div>
            <div style={{ overflowX: 'auto' }}>
              <table style={{ width: '100%', borderCollapse: 'separate', borderSpacing: '0 8px' }}>
                <thead>
                  <tr style={{ color: 'rgba(255,255,255,0.5)', fontSize: '0.8rem', textTransform: 'uppercase', letterSpacing: '1px' }}>
                    <th style={{ padding: '0 16px 8px', textAlign: 'left' }}>Department</th>
                    <th style={{ padding: '0 16px 8px', textAlign: 'center' }}>Budget (kg)</th>
                    <th style={{ padding: '0 16px 8px', textAlign: 'center' }}>Net CO₂ (kg)</th>
                    <th style={{ padding: '0 16px 8px', textAlign: 'center' }}>Surplus / Deficit</th>
                    <th style={{ padding: '0 16px 8px', textAlign: 'center' }}>Status</th>
                  </tr>
                </thead>
                <tbody>
                  {deptCapTrade.map((dept, i) => {
                    const netKg    = dept.netKg  || 0;
                    const budgetKg = dept.budgetKg || 0;
                    const isOver   = netKg > budgetKg;
                    const surplus  = budgetKg - netKg;
                    return (
                      <tr key={i} style={{ background: isOver ? 'rgba(183,28,28,0.25)' : 'rgba(27,94,32,0.25)' }}>
                        <td style={{ padding: '14px 16px', color: '#fff', fontWeight: '700', borderRadius: '10px 0 0 10px', textTransform: 'capitalize' }}>
                          {dept.department}
                        </td>
                        <td style={{ padding: '14px 16px', color: '#aaa', textAlign: 'center' }}>{budgetKg} kg</td>
                        <td style={{ padding: '14px 16px', textAlign: 'center', fontWeight: '700' }}>
                          <span style={{ color: isOver ? '#ff5252' : '#69f0ae', fontSize: '1.05em' }}>{netKg} kg</span>
                        </td>
                        <td style={{ padding: '14px 16px', textAlign: 'center', fontWeight: '700', color: isOver ? '#ff5252' : '#69f0ae' }}>
                          {isOver ? `−${Math.abs(surplus).toFixed(1)} kg` : `+${surplus.toFixed(1)} kg`}
                        </td>
                        <td style={{ padding: '14px 16px', textAlign: 'center', borderRadius: '0 10px 10px 0' }}>
                          <span style={{
                            background: isOver ? '#b71c1c' : '#1b5e20', color: isOver ? '#ffcdd2' : '#c8e6c9',
                            borderRadius: '20px', padding: '4px 12px', fontSize: '0.75rem', fontWeight: '700'
                          }}>
                            {isOver ? '⚠️ Buy Allowances' : '✅ Sell Surplus'}
                          </span>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>

            <div style={{ marginTop: '28px', padding: '20px', background: 'rgba(0,0,0,0.3)', borderRadius: '12px', border: '1px solid rgba(255,255,255,0.08)' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
                <span style={{ color: '#fff', fontWeight: '700' }}>📊 Net CO₂ vs Company Budget</span>
                <span style={{ color: budgetUsedPercent > 85 ? '#ff5252' : '#69f0ae', fontWeight: '700' }}>{budgetUsedPercent}% of budget used (net)</span>
              </div>
              <div style={{ background: '#1a1a2e', borderRadius: '8px', height: '16px', overflow: 'hidden' }}>
                <div style={{
                  width: `${budgetUsedPercent}%`, height: '100%',
                  background: budgetUsedPercent > 85 ? 'linear-gradient(90deg,#d50000,#ff5252)' : 'linear-gradient(90deg,#00c853,#69f0ae)',
                  borderRadius: '8px', transition: 'width 0.8s ease'
                }} />
              </div>
            </div>
          </div>
        </Col>
      </Row>

      <Row>
        <Col md={12}>
          <div className="gt-graph-wrapper p-4 rounded-4 shadow-lg" style={{ background: 'rgba(15,30,20,0.7)', backdropFilter: 'blur(15px)', border: '1px solid rgba(255,255,255,0.1)' }}>
            <h4 className="text-center text-white mb-1 fw-bold">Historical Cross-Module Impact Growth</h4>
            <p className="text-center" style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.78rem', marginBottom: '20px' }}>
              Monthly carpool rides, meals rescued, and trees planted by your workforce
            </p>
            <div style={{ height: '350px' }}>
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={stats.trendData || []} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.1)" vertical={false} />
                  <XAxis dataKey="month" stroke="#ffffff" />
                  <YAxis stroke="#ffffff" />
                  <RechartsTooltip contentStyle={{ backgroundColor: 'rgba(15,30,20,0.9)', border: '1px solid #2ecc71', borderRadius: '10px', color: '#fff' }} />
                  <Legend wrapperStyle={{ paddingTop: '20px', color: '#fff' }} />
                  <Bar dataKey="rides" stackId="a" fill="#3498db" name="Carpool Rides" />
                  <Bar dataKey="food"  stackId="a" fill="#f1c40f" name="Meals Saved" />
                  <Bar dataKey="trees" stackId="a" fill="#2ecc71" name="Trees Planted" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </Col>
      </Row>
    </>
  );
};

export default ESGAnalyticsView;